version: "3"
services:
  webapi:
    build:
      context: .
      dockerfile: Products.SI/Dockerfile
    image: products:latest
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      # Password for user named "sa"
      SA_PASSWORD: "Password1!"
      # Auto accept license
      ACCEPT_EULA: "Y"
